### PR TITLE
FFTsInSingleDataset

### PR DESCRIPTION
**Pull request by ldeviveiros**
Modified the HDF5 FFT writer (KTHDF5TypeWriterTransform) to save all FFTs or Power Spectra from an Egg or MAT file into a single HDF5 dataset, instead of saving one dataset per slice.  We also streamlined the writer processor - now it creates a single buffer and dataset with the required dimensions, instead of creating several buffers and datasets for each possible output, and then choosing which one to use. We also fixed references to Channel Headers, which were incorrect and causing the HDF5 writer to crash.

### CODE REVIEW

**Comment by nsoblath** [comment]
Luiz, I see that there are a number of places where you added print statements about the number of channels.  Is that issue resolved, or still a problem?

**Comment by ldeviveiros** [comment]
Still a problem.  I couldn't find where the problem is coming from, and
decided to put it aside for now and get back to it later.  I will create an
issue.  I can remove the print statements if you prefer.  Keep in mind that
the underlying problem was already there in the develop branch.

Luiz

**Comment by nsoblath** [comment]
If you could comment out the print statements in the develop branch, that'd be great.  I'm working on some Katydid things now, so I'll see if I can find anything.  If I have any other comments, I'll leave them in the issue you just created.  Thanks!

**Comment by ldeviveiros** [comment]
I assume the fact that you closed (and re-opened) the pull request to mean that I can merge it.  I am merging it then...

**Pull request merged**
