### PR TITLE
had to add the LD_LIBRARY_PATH (with round and NOT curly braces) to inherit it from th…

### PR DESCRIPTION
**Pull request by brentvan**
…e environment, otherwise it does not pick up the correct gcc version.  I think this is a bug peculiar to constance with its funky gcc install.  I also note that the error this prevents is not strictly repeatable (the build worked with the original branch a few days ago).

### CODE REVIEW

**Comment by nsoblath** [comment]
I've changed the minimum ROOT version back to 5.28.

I apologize for continuing to question the parentheses, but I haven't been able to find anything mentioning that syntax.  The only mention of accessing environment variables that I see in the [CMake syntax documentation](http://cmake.org/cmake/help/v3.0/manual/cmake-language.7.html#syntax) is using $ENV{SOME_VARIABLE} .  Do you have a reference for that usage of parentheses?  I just want to make sure I understand how everything's working.

**Comment by brentvan** [comment]
The round parentheses was something that Jan Strube guessed (he helped me debug the build).  He is not actually familiar with cmake so it was an educated guess based on (potentially false) analogy with some other interpreted language.  It appears to be correct, but if cmake documents say to use $ENV{SOME_VARIABLE} then that is clearly the preferred syntax.

**Comment by nsoblath** [comment]
Brent, can you give this version a test on constance to see if Katydid installs correctly?

**Comment by brentvan** [comment]
very dumb question - I have my local copy of this branch (constance_FindROOT_issue) under my home directory on constance .  How do I bring down your update to test.  "checkout" is not right (Already on 'constance_FindROOT_issue').  Is this "pull" or "merge" or another one?

**Comment by laroque** [comment]
Pull

**Comment by brentvan** [comment]
I started from a clean clone:

git fetch origin
git checkout -b constance_FindROOT_issue origin/constance_FindROOT_issue
git merge develop

This now builds on constance without issue

**Pull request merged**
