### PR TITLE
Feature/max snr and bin density cut

### PR DESCRIPTION
**Pull request by cclaessens**
new cuts and cut options.
cut classes moved to EventAnalysis/CutClasses

Still need to sort CMakeLists.txt in EventAnalysis in alphabetical order.

### CODE REVIEW

**Comment by cclaessens** [comment]
sorted cmakelist and resolved merge conflicts with develop

**Comment by cclaessens** [comment]
@guiguem How do I fix the travis building failure?

**Comment by guiguem** [comment]
basically we use a docker container in which morpho is installed. I think morpho implements the solution, you would have to look into the installation script in the morpho repo. I can point you to the right one if you don't find it.

**Comment by guiguem** [comment]
More precisely, you can look into https://github.com/project8/morpho/blob/develop/.travis.yml where there is a matrix of environments: I added one that builds the container from guiguem/root-docker and launches tests afterwards. 
There is an open issue too #169

**Comment by nsoblath** [comment]
Travis changes were moved to a new branch: feature/travis_fix.  This PR will be completed without them.

**Pull request merged**
